---
name: 'pass-backup:ci'

'on':
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-pre-commit:
    name: 'terraform:pre-commit'
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ secrets.TERRAFORM_VERSION }}

    - uses: actions/setup-python@v2

    - name: Install terraform tooling
      run: |
        curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && tar xzf terraform-docs.tgz terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
        curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip tflint && rm tflint.zip && sudo mv tflint /usr/bin/

    - name: Log tooling version
      run: |
        tflint --version
        terraform-docs --version
        terraform -version

    - name: Check modules
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --show-diff-on-failure --all-files
